name: First Workflow

on:
  - push

jobs: 
  first_job: 
    runs-on: ubuntu-latest
    steps:
      - name: Welcome Message
        run: echo "My first GitHub Actions Job"

      - name: List Files(Include Hidden) 
        run: ls -a  

      
  